// ==========================================
// Zeny Bounty Configuration (ระบบเงินดรอป)
// ==========================================

// --- เปิด/ปิด ระบบจำกัดแมพ ---
// 1 = ระบบสุ่มแมพ/บังคับแมพ ทำงานปกติ
// 0 = ปิดระบบแมพ (ตีมอนสเตอร์ดรอปเงิน "ทุกแผนที่" ทั่วเซิร์ฟเวอร์)
MapSystemEnable: 0

// --- ระบบ Stamina (สตามิน่า) ---
RequireStamina: 1

// --- โหมด GM บังคับเลือกแมพ (Override) ---
GmOverrideMap: none

// --- ระบบสุ่มแมพ Bounty ---
MapChangeInterval: 60
ActiveMapCount: 3

// --- ระบบโอกาสได้รับ Zeny ---
DropChance: 0

// --- อัตราหักลบโอกาสดรอปเงินเมื่อใช้งาน Auto Attack (หน่วยเป็น %) ---
// ตัวอย่าง: ถ้าตั้ง 50 หมายถึงหักออกครึ่งนึง (ถ้า DropChance = 30 จะเหลือ 15)
// ถ้าตั้ง 100 คือคนเปิด Auto Attack จะตีไม่ได้เงินเลย
AutoAttackChancePenalty: 100

// --- ระบบ Level Penalty ---
LevelDiff: 15
PenaltyPerLevel: 5
MinPenalty: 10

// --- ระบบ AoE Penalty ---
AoEPenalty: 40
AoESkills: 7,57,62,254,16,17,18,21,81,83,85,89,90,91,47,129,79,153,137


// --- ระบบตัวคูณ Zeny ---
MvpMultiplier: 20

// --- รายชื่อแมพ Bounty ออโต้ ---
Maps: prt_fild08,prt_fild01,pay_fild04,moc_fild02,gef_fild01,gef_fild02,mjolnir_01,mjolnir_02,mjolnir_03,cmd_fild01,cmd_fild02,yuno_fild01,yuno_fild02,yuno_fild03,ein_fild01,ein_fild02,lhz_fild01,lhz_fild02,hu_fild01,hu_fild02,ve_fild01,ve_fild02,ra_fild01,ra_fild02