// ========================================================
// Item Daily Option Config (ฉบับรวบยอด - รันใหม่ทั้งหมด)
// รูปแบบ: [ประเภทไอเทม], [ประเภทย่อย/ชิ้นส่วน], [เลเวลสวมใส่ขั้นต่ำ], [ชื่อกลุ่มออฟชั่นฐาน]
// ========================================================

// --------------------------------------------------------
// [ กลุ่มอาวุธ ]
// --------------------------------------------------------
IT_WEAPON, W_DAGGER,   0, OP_Dagger
IT_WEAPON, W_BOW,      0, OP_Bow
IT_WEAPON, W_STAFF,    0, OP_OH_Staff
IT_WEAPON, W_2HSTAFF,  0, OP_TH_Staff
IT_WEAPON, W_1HSWORD,  0, OP_OH_Sword
IT_WEAPON, W_2HSWORD,  0, OP_TH_Sword
IT_WEAPON, W_MACE,     0, OP_Mace
IT_WEAPON, W_2HMACE,   0, OP_Mace
IT_WEAPON, W_KATAR,    0, OP_Katar
IT_WEAPON, W_1HSPEAR,  0, OP_OH_Spear
IT_WEAPON, W_2HSPEAR,  0, OP_TH_Spear
IT_WEAPON, W_1HAXE,    0, OP_Axe
IT_WEAPON, W_2HAXE,    0, OP_Axe
IT_WEAPON, W_KNUCKLE,  0, OP_Knuckle
IT_WEAPON, W_MUSICAL,  0, OP_Musical
IT_WEAPON, W_WHIP,     0, OP_Whip
IT_WEAPON, W_BOOK,     0, OP_Book

// --------------------------------------------------------
// [ กลุ่มเครื่องป้องกัน ]
// --------------------------------------------------------
IT_ARMOR, EQP_GARMENT,  0, OP_GARMENT
IT_ARMOR, EQP_ARMOR,    0, OP_ARMOR
IT_ARMOR, EQP_HAND_L,   0, OP_SHIELD
//IT_ARMOR, EQP_HAND_R,   0, OP_SHIELD
IT_ARMOR, EQP_SHOES,    0, OP_SHOES
IT_ARMOR, EQP_HEAD_TOP, 0, OP_HEADTOP