// ------------------- Common Script Files ----------------------
//import: npc/thuay.conf
import: npc/cbt.conf
import: npc/safezone.conf
import: npc/main.conf
import: npc/scripts_mapflags.conf
import: npc/scripts_monsters.conf
import: npc/scripts_warps.conf
import: npc/scripts_guild.conf
//import: npc/scripts_nguild.conf

// ------------------- Renewal Script Files ---------------------
import: npc/re/scripts_mapflags.conf
//import: npc/pre-re/scripts_monsters.conf
import: npc/re/scripts_monsters.conf
import: npc/re/scripts_warps.conf



