//npc: npc/cbt/ev1/cbt_99.txt
//npc: npc/cbt/ev1/freenpc.txt
//npc: npc/cbt/ev1/guild_cbt.txt
//npc: npc/cbt/ev1/refine_cbt.txt
//npc: npc/cbt/ev1/cbt_shere.txt
//---------------------------OBT-----------------//

npc: npc/cbt/obt/master_training.txt
npc: npc/cbt/obt/faction_mapflag.txt
npc: npc/cbt/obt/faction_war.txt
npc: npc/cbt/obt/npcevent/craft_charm.txt
npc: npc/cbt/obt/npcevent/globel_zeny.txt
npc: npc/cbt/obt/npcevent/func_cellpvp.txt



//------------------npctool-----------------//
npc: npc/cbt/obt/npctool/warp.txt
npc: npc/cbt/obt/npctool/shop.txt
npc: npc/cbt/obt/npctool/option.txt
npc: npc/cbt/obt/npctool/optionstone_crafe.txt
npc: npc/cbt/obt/npctool/GuildWar_Auto.txt
npc: npc/cbt/obt/npctool/item_functions.txt
//npc: npc/cbt/obt/npctool/cos_option.txt

//npc: npc/cbt/obt/npctool/cos_stone_exchange.txt
npc: npc/cbt/obt/npctool/fakeshop.txt
npc: npc/cbt/obt/npctool/ticket_plus7.txt
npc: npc/cbt/obt/npctool/reoption.txt

//npc: npc/cbt/obt/npctool/charname_color_npc.txt
npc: npc/cbt/obt/npctool/boss_egg.txt
npc: npc/cbt/obt/npctool/legendary_quest.txt
//---------npcevent-----------//

//npc: npc/cbt/obt/npcevent/songkran.txt
//npc: npc/cbt/obt/npcevent/change_item.txt
//npc: npc/cbt/obt/npcevent/change_refine.txt
//npc: npc/cbt/obt/npcevent/new_player.txt
//npc: npc/cbt/obt/npcevent/crimson_craft.txt
npc: npc/cbt/obt/npcevent/chicken.txt
//npc: npc/cbt/obt/npcevent/eventrefine.txt
npc: npc/cbt/obt/npcevent/card_exchange.txt

npc: npc/cbt/obt/updowndrop.txt
npc: npc/cbt/obt/AntiBot_Moniter.txt
npc: npc/cbt/obt/AntiBot_Moniter2.txt

npc: npc/cbt/obt/master_kill.txt

npc: npc/cbt/obt/eventrate.txt

npc: npc/cbt/obt/npcevent/battle_pass.txt
npc: npc/cbt/obt/egg_box.txt
//npc: npc/cbt/obt/craft_bin.txt

npc: npc/cbt/obt/stamina_lucky_map.txt

npc: npc/cbt/obt/stall.txt
npc: npc/cbt/obt/item_map.txt

//npc: npc/cbt/obt/shadow_random.txt


npc: npc/cbt/obt/refine_dust.txt

npc: npc/cbt/obt/boss_egg_drops.txt
//---------------week2---------//
npc: npc/cbt/obt/Costume_grade.txt
//npc: npc/cbt/obt/darkwing.txt
//npc: npc/cbt/obt/refine_bonus.txt
npc: npc/cbt/obt/zeny_monitor.txt
npc: npc/cbt/obt/member_farm_spawn.txt

////------dunnew--------//
//npc: npc/cbt/obt/dunnew/Endlesstower.txt
//npc: npc/cbt/obt/dunnew/new_dun01.txt
//npc: npc/cbt/obt/dunnew/Guildvsboss.txt
//npc: npc/cbt/obt/dunnew/ninja_dun.txt
//npc: npc/cbt/obt/dunnew/OldGlastHeim.txt
//npc: npc/cbt/obt/dunnew/FacewormsNest.txt
//npc: npc/cbt/obt/dunnew/riss.txt

//npc: npc/cbt/obt/craft_eluori.txt
//npc: npc/cbt/obt/craft_charm2.txt


//npc: npc/cbt/event/lotto_item.txt
//npc: npc/cbt/event/casino_dice_250k.txt