//---------------NPC¾×é¹°Ò¹--------------------//
//npc: npc/main/cities/

//npc: npc/main/cities/alberta.txt
//npc: npc/main/cities/aldebaran.txt
//npc: npc/main/cities/comodo.txt
//npc: npc/main/cities/geffen.txt
//npc: npc/main/cities/izlude.txt
//npc: npc/main/cities/lutie.txt
//npc: npc/main/cities/morocc.txt
//npc: npc/main/cities/payon.txt
//npc: npc/main/cities/prontera.txt
//npc: npc/main/cities/yuno.txt

