//npc: npc/nguild/nguild_dunsw.txt
//npc: npc/nguild/nguild_ev_agit.txt
//npc: npc/nguild/nguild_flags.txt
//npc: npc/nguild/nguild_guardians.txt
//npc: npc/nguild/nguild_kafras.txt
//npc: npc/nguild/nguild_managers.txt
//npc: npc/nguild/nguild_treas.txt
//npc: npc/nguild/nguild_warper.txt